export const GET_UDC_GENERAL_INITIAL_STATE = 'GET_UDC_GENERAL_INITIAL_STATE';
export const GET_UDC_HIDES_INITIAL_STATE = 'GET_UDC_HIDES_INITIAL_STATE';
export const SAVE_NEW_UDC_SESSION = 'SAVE_NEW_UDC_SESSION';
export const SAVE_UDC_DOG = 'SAVE_UDC_DOG';
export const SAVE_UDC_DOG_TRAINING = 'SAVE_UDC_DOG_TRAINING';

